### ISSUE TITLE
How to revert commit

### ISSUE THREAD

**Issue by KingofGamesYami** [FTC-4160/ftc_app#10]
Everything in this commit isn't needed, AFAIK.  Github desktop just thought we needed it - https://github.com/FTC-4160/ftc_app/commit/ed8553795073707a3502023615b8220649911140

**Comment by btelman96** [comment]
Sorry for the delay, but this may help

http://stackoverflow.com/questions/4114095/revert-git-repo-to-a-previous-commit

**Comment by KingofGamesYami** [comment]
I ended up just deleting the files individually through the github website.  Boring, repetitive, and got exactly what I wanted done.

**Comment by btelman96** [comment]
Hey, good luck competing tomorrow
