### ISSUE TITLE
CameraOp doesn't work

### ISSUE THREAD

**Issue by KingofGamesYami** [FTC-4160/ftc_app#3]
Currently, CameraOp will error with a null.  All other opmodes are unaffected, but I must not be finding the camera.

**Comment by btelman96** [comment]
Can you give me a line number or a stack trace? I get that you may not have that right now. I will look at the code.

**Comment by btelman96** [comment]
Try implementing the open camera fuction that is located in RobotControllerActivity in advance. That is the only thing I can think of now. Sorry if I missed its implementation.

**Comment by KingofGamesYami** [comment]
Yeah, that'd be it.  [here](http://ftcforum.usfirst.org/showthread.php?4588-How-to-use-the-camera-as-a-sensor&p=16694&viewfull=1#post16694) someone fixed the same issue.  When I get home, I'll do this in Android Studio and push it.

**Comment by KingofGamesYami** [comment]
Leave this open until we actually test it

**Comment by KingofGamesYami** [comment]
Tested this yesterday, works fine.  /close
