### ISSUE TITLE
Playing Raw Sound Files

### ISSUE THREAD

**Issue by KingofGamesYami** [FTC-4160/ftc_app#9]
Every time I try to play a raw sound file, Android Studio says something about Groovy SDK not being installed.  I'm probably doing something wrong, as it seems like you should be able to just play a sound file without any additional SDKs.

**Comment by btelman96** [comment]
All you need to use is the MediaPlayer implementation. That is built into
the Android sdk, so you don't need more files.

Groovy is an entirely different programming language. Make sure to check
the gradle file or the project settings for anything weird.

**Comment by KingofGamesYami** [comment]
I think I've solved this, although it took github desktop to commit the sound file.  Playing the imperial march at full volume during autonomous should get us some extra points, right?
